---
# Database type (mysql, yml, json, sqlite)
# Тип базы данных
type: yml

# Database IP
# IP базы данных 
# (mysql)
ip: '127.0.0.1'
# Database username 
# Имя пользователя 
# (mysql)
username: 'auth'
# Username's password
# Пароль пользователя
# (mysql)
password: '12345'
# Database/Folder name
# Имя базы данных/папок
# (mysql, yaml, json, sqlite)
database: 'authdb'
# Database tables/folder prefix
# Префикс таблиц базы данных/папок
# (mysql, yaml, json, sqlite)
table_prefix: ''

# Plugin language (ru/en)
# Язык плагина
language: 'en'

# Enable autologin? (using IP and Client ID)
# Включить автоматический вход? (используя IP и Client ID)
enable_autologin: false
# Enable this if you want to hide players if they aren't logged in
# Включите это, если вы хотите скрыть неавторизировавшихся игроков
hide_players: false

# Time format (e.g in /myadmin info)
# Формат времени (например, в /myadmin info)
time_format: 'd.m.Y H:i:s'

##      FOR UNAUTHORIZED USERS      ##
## ДЛЯ НЕАВТОРИЗИРОВАВШИХСЯ ИГРОКОВ ##

# Block breaking blocks
# Блокировка ломания блоков
cancel_block: true

# Block dropping items from inventory
# Блокировка выбрасывания предметов из инвентаря
cancel_drop: true

# Block interacting with things
# Блокировка действий с предметами
cancel_interacting: true

# Block usage of buckets
# Блокировка взаимодействий с вёдрами
cancel_buckets: true

# Block moving
# Блокировка движений
cancel_moving: true

# Block eating food
# Блокировка съедания еды
cancel_moving: true
...