---
# Database type (mysql)
# Тип базы данных
type: mysql

# Database IP
# IP базы данных
ip: '127.0.0.1'
# Database username 
# Имя пользователя 
username: 'auth'
# Username's password
# Пароль пользователя
password: '12345'
# Database name
# Имя базы данных
database: 'authdb'
# Database tables prefix
# Префикс таблиц базы данных
table_prefix: ''

# Plugin language (ru/en)
# Язык плагина
language: 'en'

# Enable autologin? (using IP and Client ID)
# Включить автоматический вход? (используя IP и Client ID)
enable_autologin: false
...