---
# MySQL DB IP
ip: '127.0.0.1'
# MySQL username
username: 'auth'
# MySQL password
password: '12345'
# MySQL DB name
database: 'authdb'
# MySQL DB tables prefix (e.g. for different servers)
table_prefix: ''

# Message language (ru/en)
language: 'en'
...